name: Hola mundo keren

on: [push]

jobs:
  uno:
    runs-on: ubuntu-latest

    steps:
      - name: Mensaje
        run: echo "Hola mundito"
      - name: Touch File #Crea
        run: |
          touch hola.txt
          ls -al
      
      - name: Set text #Agrega 
        run: |
          echo "Hola mundito" >> hola.txt
          ls -al
      
      - name: Read File #Lee 
        run: |
          cat hola.txt
          ls -al

  dos:
    runs-on: ubuntu-latest
    needs: [uno]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
      - name: Directorio
        run: ls -al